### PR TITLE
Qt5

### PR DESCRIPTION
**Pull request by followtheart**
Compatible with Qt5

### CODE REVIEW

**Comment by yacoin** [comment]
Thanks for PR, keep them coming! I am closing this however since testing will be merged into master in the next few weeks once the builds and bootstrap file are complete. Testing is Qt5 compatible.

**Comment by andyzouf** [comment]
how about  my coin?but  
Cryptsy Cryptocurrency Settlement
Case No.: 9:16-cv-80060


HOME
SUBMIT A CLAIM
IMPORTANT DOCUMENTS
FAQS
CONTACT US
Cryptsy Class Action Settlement Update:
On June 2, 2017, the Court granted final approval to the class action settlement. A copy of the Order approving the settlement is posted on this website. In granting final approval, the Court has authorized the Court-Appointed Receiver and Class Counsel to complete the liquidation of assets that comprise the settlement fund. We expect this process to be complete by the fourth quarter, 2017. Once this process is complete, the parties must file with the Court a motion that provides the results of this process and seeks the Court’s authorization to disburse the Settlement Fund in accordance with the Class Action Settlement Agreements.
At the same time, the Claims Administrator and Class Counsel are reviewing the claims submitted by Settlement Class Members.
We expect to start distributing the Settlement Fund in the first quarter, 2018. If this changes, we will post additional updates here.
If you are a CRYPTSY account holder and are unable to access your CRYPTOCURRENCY, you could get money from two different class action settlements, and an ongoing class action lawsuit may affect your rights. PLEASE READ THE NOTICECAREFULLY.
Important Dates

April 17, 2017 - Deadline to Request Exclusion (must be postmarked by this date)

May 3, 2017 - Deadline to Object (must be postmarked by this date)

May 17, 2017 - Deadline to submit a Claim Form (must be submitted online by or postmarked by this date)

June 2, 2017 at 10:00 A.M. - Fairness Hearing



OVERVIEW

The Notice describes two partial settlements of a lawsuit and how you can get money from those settlements or exclude yourself from one or both of them. The Notice also describes the portion of the lawsuit that is continuing and how you can continue in that lawsuit or exclude yourself from that lawsuit.

BACKGROUND

On August 25, 2016, the Honorable Kenneth A. Marra of the United States District Court for the Southern District of Florida entered an order certifying a class of Cryptsy account holders who are unable to access their cryptocurrency in a class action lawsuit.

The class action lawsuit claims that:

(1) Defendant Project Investors, Inc. d/b/a Cryptsy (“Cryptsy”) and Paul Vernon (“Vernon”) stole and converted for their own use the cryptocurrencies of the Cryptsy account holders;

(2) Defendant Lori Ann Nettles (“Nettles”) was unjustly enriched as a result of assets that she received that were purchased with the proceeds of cryptocurrency taken from the Cryptsy account holders during her marriage to, and in her divorce from, Vernon; and

(3) Defendants Ridgewood Investments, Inc. (“Ridgewood”) and Kaushal Majmudar (“KM”) were unjustly enriched as a result of consulting fees they received from Cryptsy.

On April 24, 2016, the Court also appointed James D. Sallah, not individually but solely in his capacity as the Court-appointed Receiver, to act as the Receiver in this matter. The Receiver took control of Cryptsy, and worked with the lawyers for the plaintiffs in this class action to recover monies and assets for the Cryptsy account holders, which are part of the Settlements.

Certain of the defendants have settled, and the litigation is proceeding against the remaining defendants. The purpose of the notice is to advise you of your rights with respect to (A) the settlement with certain defendants and (B) the continuing litigation against the remaining defendants.

If you are a Class Member, you have a right to participate in the settlements, and you have a right to participate as a class member in the continuing lawsuit against the remaining defendants. You do not have to choose between the settlement and the continuing litigation, and your rights with respect to each are independent.

This is not a lawsuit against you. Your participation in this lawsuit or acceptance of money from either or both of the settlements will not affect your employment status or compensation in any way.

Please read the Notice carefully. The Notice explains your legal rights and options—and the deadlines to exercise them. Your legal rights will be affected whether you act or don’t act, and you have choices to make now.

The Notice is divided into two parts: The first part discusses the proposed settlement with certain defendants; the second part discusses the continuing litigation against the remaining defendants. Please read both parts of the Notice carefully.

The Settlement with Certain Defendants

Two settlements, (1) a settlement with Defendant Nettles, and (2) a settlement with Defendants Ridgewood and KM (Ridgewood and KM are referred to collectively herein as Ridgewood), have been reached in partial settlement of the class action lawsuit. Nettles and Ridgewood deny that they violated any laws or engaged in any wrongdoing. For purposes of this notice, Nettles and Ridgewood are referred to collectively as the “Settling Defendants.”

You are a Class Member if you are a Cryptsy account owner who held Bitcoins, alternative cryptocurrencies, or any other form of monies or currency at Cryptsy as of November 1, 2015, through June 2, 2017, and are unable to access your cryptocurrency. Excluded from the Class are all employees of Cryptsy, including its shareholders, officers and directors and members of their immediate families.

The Court in charge of this case still has to approve the settlements with the Settling Defendants. Payments will be made if the Court approves the settlements and orders that the settlement funds be distributed, and if any appeals of the Court’s approval of these settlements are resolved in Plaintiffs’ favor. Please be patient.

All references are to “settlements” in the plural. However, understand that the two settlements are independent and separate. The Court may approve one or both of the two settlements. Moreover, you may opt out of, comment on, or object to one or both settlements.

SUMMARY OF YOUR LEGAL RIGHTS AND OPTIONS WITH RESPECT TO THE
SETTLING DEFENDANTS
|
DO NOTHING
|

Get no payment from the Settling Defendants. Give up your rights to ever recover from the Settling Defendants for the legal claims in this case if the settlements are approved.

You will remain a Class Member in the lawsuit against Cryptsy and Vernon, which are referred to collectively as the “Non-Settling Defendants,” and retain the possibility of getting money or other benefits from the Non-Settling Defendants that may come from trial or settlement.

|
|
EXCLUDE YOURSELF FROM EITHER OR BOTH OF THE SETTLEMENTS
|

Get no payment from the settlements. This is the only way that you can file your own lawsuit or ever be part of any other lawsuit about the legal claims in this case against any of the Settling Defendants. You may exclude yourself from one or both settlements.

Even if you exclude yourself from one or both of the settlements, you will remain in the Class for purposes of the continuing lawsuit against the Non-Settling Defendants and will be bound by the outcome unless you submit a written exclusion request.

Click here for more information about excluding yourself.

|
|
SUBMIT A CLAIM FORM FOR YOUR SHARES OF THE SETTLEMENTS
|

The only way to receive money from the settlements when the funds are distributed is by submitting a claim form by May 17, 2017.

Click here to submit your Claim online or click here to download a Claim Form.

|
|
OBJECT TO OR COMMENT ON THE SETTLEMENTS
|

Write to the Court about why you like or do not like the settlements by no later than May 3, 2017. You may also ask to speak to the Court about your written comments or objections about the fairness of either or both of the settlements at the “Fairness Hearing” onJune 2, 2017, though you do not have to do so. To comment on or object to either or both settlements and request to speak at the “Fairness Hearing,” you must act before May 3, 2017.

Click here for more information about objecting to the settlement.

|
|
GO TO THE COURT’S FAIRNESS HEARING ABOUT THE SETTLEMENTS
|

If you would like, you may ask to speak in Court about the fairness of one or both of the settlements. You do not need to speak to the Court to receive benefits under the settlements.

Click here for instructions about speaking at the hearing.

|



The Continuing Litigation Against the Non-Settling Defendants

The lawsuit is continuing against Cryptsy and Vernon, which are referred to as the “Non-Settling Defendants.”

You are a Class Member if you are a Cryptsy account owner who held Bitcoins, alternative cryptocurrencies, or any other form of monies or currency at Cryptsy as of November 1, 2015, through June 2, 2017, and are unable to access your crypto currency. Excluded from the Class are all employees of Cryptsy, including its shareholders, officers and directors and members of their immediate families.

The outcome of the class action lawsuit against the Non-Settling Defendants is not yet known. The Non-Settling Defendants have failed and refused to respond to the lawsuit, the Court has entered a default against them, and Vernon has fled to China. Thus, it may be unlikely that any additional cryptocurrency or monies will be obtained from the Non-Settling Defendants. You will be notified if money or benefits are obtained from any of the Non-Settling Defendants through settlements or trial. Please be patient.

You have the right to exclude yourself from the continuing lawsuit against the Non-Settling Defendants. If you choose to do so, you must exercise your right by April 17, 2017. Instructions on how to opt out are set forth in response toQuestion 21. You can receive the benefits of one or both of the settlements with the Settling Defendants even if you opt-out of the continuing lawsuit against the Non-Settling Defendants.

This Class Action is separate and distinct from the class action lawsuit filed on December 13, 2016 againstCOINBASE, INC., in which Plaintiffs and the Receiver in this Class Action are attempting to recover additional monies for the same class certified by the Court in this Action. Accordingly, your rights or claims in the Coinbase Class Action will not be impacted by this Action.

SUMMARY OF YOUR LEGAL RIGHTS AND OPTIONS WITH RESPECT TO THE 
NON-SETTLING DEFENDANTS
|
DO NOTHING
|

If you do nothing, you will remain a Class Member in the lawsuit against the Non-Settling Defendants and retain the possibility of getting money or other benefits from the Non-Settling Defendants that may come from trial or settlement. By remaining in the Class, you will be bound by the outcome of the continuing lawsuit with the Non-Settling Defendants and will give up your right to file your own lawsuit. There is no money available now from Cryptsy or Vernon, and no guarantee that there will be. The outcome of the continuing class action lawsuit against these Non-Settling Defendants is not yet known. If additional money or benefits are obtained from the Non-Settling Defendants, you will be notified again.

|
|
EXCLUDE YOURSELF FROM THE ONGOING LAWSUIT
|

If you exclude yourself from the ongoing lawsuit, you will receive no payment from any Non-Settling Defendants even if any monies are collected as the result of a trial or settlement, but you will retain the right to file your own lawsuit. You will remain in the Class on whose behalf the lawsuit will continue against the Non-Settling Defendants unless you submit a written request to exclude yourself from it as described in the response to Question 21. You must submit a timely written request to exclude yourself from the Class, if you wish to do so, by April 17, 2017. This is the only way that you can file your own lawsuit or ever be part of any other lawsuit about the legal claims in this case against any of the Non-Settling Defendants.

|



Detailed Information

The above is a summary of the lawsuits against the Settling and Non-Settling Defendants. The Notice is designed to provide more information to help you evaluate your options and answer any questions that you may have.

GETTING MORE INFORMATION

�6�1 Visit the Receivership website at www.cryptsyreceivership.com

�6�1 Visit the Public Access to Court Electronic Records (“PACER”) website: www.pacer.gov to review the Settlement Agreements by clicking on the “Find a Case” option and searching by Case Number for 9:16-cv-80060

�6�1 Contact Co-Lead Class Counsel at:

Marc A. Wites
Wites & Kapetan, P.A.
4400 N. Federal Highway
Lighthouse Point, Florida 33064
(954) 570-8989

�6�1 Contact the Claims Administrator at:

Cryptsy Cryptocurrency Administrator
1801 Market Street, Suite 660
Philadelphia, PA 19103
Email: info@cryptsysettlement.com
Toll-Free: 1-888-868-4936 
Facsimile: 1-215-525-0209

PLEASE DO NOT CONTACT THE COURT. YOU SHOULD DIRECT ANY QUESTIONS YOU MAY HAVE TO THE NOTICE AND CLAIMS ADMINISTRATOR AND/OR TO PLAINTIFFS’ COUNSEL.
You may also seek the advice and counsel of your own attorney at your own expense, if you desire.

Copyright �0�8 2017





At 2016-10-27 03:31:40, "yacoin" <notifications@github.com> wrote:


Thanks for PR, keep them coming! I am closing this however since testing will be merged into master in the next few weeks once the builds and bootstrap file are complete. Testing is Qt5 compatible.

**Comment by andyzouf** [comment]
hi，good man，how  about my  bitcoin in the   Cryptsy？I am  chinese man，who can  help me。Carte blanche，





At 2016-10-27 03:31:40, "yacoin" <notifications@github.com> wrote:


Thanks for PR, keep them coming! I am closing this however since testing will be merged into master in the next few weeks once the builds and bootstrap file are complete. Testing is Qt5 compatible.

**Comment by andyzouf** [comment]
Dear Sir:

Hello.  You are receiving this email because you previously contacted us about the Cryptsy Class Action.  You should have received via mail or email a notice about a settlement in the case and a claim form.  If you did not receive the notice, you can obtain a copy by visiting http://www.cryptsysettlement.com/ or by emailing the claims administrator at info@cryptsysettlement.com<mailto:info@cryptsysettlement.com>.
If you wish to make a claim in the class action, you must submit a claim form to the claims administrator. You must make a claim even if you previously provided information to the lawyers in this case about your cryptocurrency.   As noted above, the claim form is available on the settlement website at http://www.cryptsysettlement.com/

If you are beyond the deadline to submit a claim form, please contact the Cryptsy Cryptocurrency Administrator to discuss issues related to late claim forms.

Any other questions regarding the claims process can be addressed to:

Cryptsy Cryptocurrency Administrator
1801 Market Street, Suite 660
Philadelphia, PA 19103
Email: info@cryptsysettlement.com<mailto:info@cryptsysettlement.com>
Toll-Free: 1-888-868-4936
Facsimile: 1-215-525-0209
Best Regards,
Robert Carey, Esq., Deputy Receiver


From: 12 [mailto:andyzouf@163.com]
Sent: Saturday, June 17, 2017 5:41 AM
To: yacoin/yacoin; robert@robertcareylaw.com; jds
Cc: yacoin/yacoin
Subject: Re:Re: [yacoin/yacoin] Qt5 (#69)


hi，good man，how  about my  bitcoin in the   Cryptsy？I am  chinese man，who can  help me。Carte blanche，



At 2016-10-27 03:31:40, "yacoin" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for PR, keep them coming! I am closing this however since testing will be merged into master in the next few weeks once the builds and bootstrap file are complete. Testing is Qt5 compatible.

-

**Comment by andyzouf** [comment]
DEAR sir:
     I am an chinese,so much time i have lost the thing.I don't  know  what's happen.I  am  beyond the deadline to submit a claim form.How to deal with?I  have  lost  much  money about 30 btc，How to deal with?please  help me，Great American friends.


thank you
       






At 2017-06-27 03:48:00, "robert@robertcareylaw.com" <robert@robertcareylaw.com> wrote:


Dear Sir:

 

Hello.  You are receiving this email because you previously contacted us about the Cryptsy Class Action.  You should have received via mail or email a notice about a settlement in the case and a claim form.  If you did not receive the notice, you can obtain a copy by visiting http://www.cryptsysettlement.com/ or by emailing the claims administrator at info@cryptsysettlement.com.

If you wish to make a claim in the class action, you must submit a claim form to the claims administrator. You must make a claim even if you previously provided information to the lawyers in this case about your cryptocurrency.   As noted above, the claim form is available on the settlement website at http://www.cryptsysettlement.com/

 

If you are beyond the deadline to submit a claim form, please contact the Cryptsy Cryptocurrency Administrator to discuss issues related to late claim forms.

 

Any other questions regarding the claims process can be addressed to:

 

Cryptsy Cryptocurrency Administrator

1801 Market Street, Suite 660

Philadelphia, PA 19103

Email: info@cryptsysettlement.com

Toll-Free: 1-888-868-4936

Facsimile: 1-215-525-0209

Best Regards,

Robert Carey, Esq., Deputy Receiver

 

 

From: 12 [mailto:andyzouf@163.com]
Sent: Saturday, June 17, 2017 5:41 AM
To: yacoin/yacoin; robert@robertcareylaw.com; jds
Cc: yacoin/yacoin
Subject: Re:Re: [yacoin/yacoin] Qt5 (#69)

 


hi，good man，how  about my  bitcoin in the   Cryptsy？I am  chinese man，who can  help me。Carte blanche，





At 2016-10-27 03:31:40, "yacoin" <notifications@github.com> wrote:



Thanks for PR, keep them coming! I am closing this however since testing will be merged into master in the next few weeks once the builds and bootstrap file are complete. Testing is Qt5 compatible.

**Pull request closed without merging**
